routes:
  /: 
    uses: index
    as: staticpages.home
  /new: 
    uses: getNew
    as: staticpages.new
  /edit/{id}: 
    uses: getEdit
    as: staticpages.edit
  /delete/{id}:
    uses: deletePage
    as: staticpages.delete
  post@update:
    uses: update
    as: staticpages.update
  post@store:
    uses: addNew
    as: staticpages.store
